[package]
name = "gba-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Frontend launcher: ROM selection, input setup, A/V settings"

[dependencies]
dirs = "6.0.0"
eframe = "0.34.3"
gilrs = "0.11.2"
input-config = { version = "0.1.0", path = "../input-config" }
rfd = "0.17.2"
