[workspace]
resolver = "2"
members = [
    "crates/armv4t",
    "crates/gba-core",
    "crates/gamedb",
    "crates/input-config",
    "crates/launcher",
    "crates/menu",
    "crates/pack",
    "crates/recomp",
    "crates/recomp-core",
    "crates/screen",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# Testing profile
[profile.release]
debug = true
lto = "fat"
codegen-units = 1

# Distribution profile
[profile.dist]
inherits = "release"
debug = false
strip = true
