//! C11 emission.
//!
//! v1: the hot instruction classes are inlined as native C with exact
//! NZCV semantics (mirroring `gba_core::exec`); everything rare or
//! mode-touching (SWI, MRS/MSR, swaps, register-specified shifts,
//! user-bank transfers, PC-writing ALU/loads) executes through the
//! runtime's `interp_one` shell with a PC check, so it can never be
//! wrong — divergence simply returns to the dispatcher.
//!
//! Layout contract (asserted in gba-core's capi module): casting the
//! machine pointer to `uint32_t*` yields r0..r15 at indices 0..15 and
//! CPSR at index 16.
//!
//! Every exit path stores r15 (and the Thumb bit in CPSR where it can
//! change) before returning the next lookup key (`addr | thumb`).

use std::fmt::Write;

use armv4t::{AluOp, Cond, Instr, MemOffset, MemWidth, Op, Operand2, Shift, ShiftKind, PC};

use crate::analyze::{Analysis, Block};

const PREAMBLE: &str = r#"// Generated by recomp — derivative of the input image; do not distribute.
#include <stdint.h>

// The block table is the only thing the play runtime resolves by name. On
// Windows a DLL exports nothing unless it is marked, so the two table symbols
// carry an explicit export attribute; on every other platform `-shared`
// exports them already and this expands to nothing (preprocessed away when
// _WIN32 is undefined, so the Unix output is unchanged). This covers every
// Windows compiler — bundled TinyCC and a system clang/gcc alike.
#ifdef _WIN32
#define RCG_EXPORT __declspec(dllexport)
#else
#define RCG_EXPORT
#endif

typedef struct {
    uint32_t (*interp_one)(void*);
    uint32_t (*read8)(void*, uint32_t);
    uint32_t (*read16)(void*, uint32_t);
    uint32_t (*read32)(void*, uint32_t);
    void (*write8)(void*, uint32_t, uint32_t);
    void (*write16)(void*, uint32_t, uint32_t);
    void (*write32)(void*, uint32_t, uint32_t);
    void (*tick)(void*, uint32_t);
    uint32_t (*guard)(void*, uint32_t, uint32_t, uint64_t);
    uint32_t (*chain_gate)(void*);
} RtApi;
typedef struct { uint32_t key; uint32_t (*fn)(const RtApi*, void*); } RcgBlock;

static inline uint32_t ror32(uint32_t v, uint32_t n) {
    n &= 31u;
    return n ? (v >> n) | (v << (32u - n)) : v;
}
static inline void f_nz(uint32_t* c, uint32_t r) {
    c[16] = (c[16] & 0x3FFFFFFFu) | (r & 0x80000000u) | ((r == 0u) ? 0x40000000u : 0u);
}
static inline void f_c(uint32_t* c, uint32_t v) {
    c[16] = (c[16] & ~0x20000000u) | (v ? 0x20000000u : 0u);
}
static inline uint32_t op_adds(uint32_t* c, uint32_t a, uint32_t b, uint32_t cin) {
    uint64_t w = (uint64_t)a + (uint64_t)b + (uint64_t)cin;
    uint32_t r = (uint32_t)w;
    c[16] = (c[16] & 0x0FFFFFFFu)
        | (r & 0x80000000u) | ((r == 0u) ? 0x40000000u : 0u)
        | ((w >> 32) ? 0x20000000u : 0u)
        | (((((~(a ^ b)) & (a ^ r)) >> 31) & 1u) ? 0x10000000u : 0u);
    return r;
}
static inline void f_nz64(uint32_t* c, uint64_t r) {
    c[16] = (c[16] & 0x3FFFFFFFu) | ((uint32_t)(r >> 32) & 0x80000000u)
        | ((r == 0u) ? 0x40000000u : 0u);
}
"#;

fn cond_expr(c: Cond) -> &'static str {
    // CPSR bits: N=31 Z=30 C=29 V=28.
    match c {
        Cond::Eq => "(cz)",
        Cond::Ne => "(!cz)",
        Cond::Cs => "(cc)",
        Cond::Cc => "(!cc)",
        Cond::Mi => "(cn)",
        Cond::Pl => "(!cn)",
        Cond::Vs => "(cv)",
        Cond::Vc => "(!cv)",
        Cond::Hi => "(cc && !cz)",
        Cond::Ls => "(!cc || cz)",
        Cond::Ge => "(cn == cv)",
        Cond::Lt => "(cn != cv)",
        Cond::Gt => "(!cz && cn == cv)",
        Cond::Le => "(cz || cn != cv)",
        Cond::Al | Cond::Nv => "(1)",
    }
}

struct Ctx<'a> {
    out: &'a mut String,
    thumb: bool,
    /// Cycles accumulated since the last tick flush.
    cycles: u64,
}

impl Ctx<'_> {
    fn flush_ticks(&mut self) {
        if self.cycles > 0 {
            let _ = writeln!(self.out, "    a->tick(m, {}u);", self.cycles);
            self.cycles = 0;
        }
    }

    /// Register read as a C expression; PC becomes the architectural
    /// constant for this instruction.
    fn reg(&self, r: u8, instr: &Instr) -> String {
        if r == PC {
            format!("0x{:08x}u", instr.pc_value())
        } else {
            format!("c[{r}]")
        }
    }
}

/// Emit the interp_one shell for one instruction.
fn emit_shell(cx: &mut Ctx, instr: &Instr, expect: u32, last: bool) {
    cx.flush_ticks();
    let _ = writeln!(cx.out, "    c[15] = 0x{:08x}u;", instr.addr);
    if last {
        cx.out.push_str("    return a->interp_one(m);\n");
    } else {
        let _ = writeln!(
            cx.out,
            "    pc = a->interp_one(m); if (pc != 0x{expect:08x}u) return pc;"
        );
    }
}

/// Operand2 as (value-expr, optional carry-out-expr). None = shell needed.
fn op2_exprs(cx: &Ctx, instr: &Instr, op2: Operand2) -> Option<(String, Option<String>)> {
    match op2 {
        Operand2::Imm { value, ror } => {
            let carry = if ror != 0 {
                Some(format!("{}u", (value >> 31) & 1))
            } else {
                None
            };
            Some((format!("0x{value:08x}u"), carry))
        }
        Operand2::Reg { rm, shift } => {
            let rmv = cx.reg(rm, instr);
            match shift {
                Shift::Imm { kind, amount } => Some(shift_exprs(&rmv, kind, amount)),
                Shift::Reg { .. } => None, // PC+12 and amount-range semantics: shell
            }
        }
    }
}

fn shift_exprs(rm: &str, kind: ShiftKind, amount: u8) -> (String, Option<String>) {
    let a = amount as u32;
    match kind {
        ShiftKind::Lsl if a == 0 => (rm.to_string(), None),
        ShiftKind::Lsl => (
            format!("({rm} << {a}u)"),
            Some(format!("(({rm} >> {}u) & 1u)", 32 - a)),
        ),
        ShiftKind::Lsr if a == 0 => ("0u".into(), Some(format!("({rm} >> 31u)"))),
        ShiftKind::Lsr => (
            format!("({rm} >> {a}u)"),
            Some(format!("(({rm} >> {}u) & 1u)", a - 1)),
        ),
        ShiftKind::Asr if a == 0 => (
            format!("((uint32_t)((int32_t){rm} >> 31))"),
            Some(format!("({rm} >> 31u)")),
        ),
        ShiftKind::Asr => (
            format!("((uint32_t)((int32_t){rm} >> {a}))"),
            Some(format!("(({rm} >> {}u) & 1u)", a - 1)),
        ),
        ShiftKind::Ror if a == 0 => (
            // RRX: carry in to bit 31.
            format!("((((c[16] >> 29) & 1u) << 31) | ({rm} >> 1u))"),
            Some(format!("({rm} & 1u)")),
        ),
        ShiftKind::Ror => (
            format!("ror32({rm}, {a}u)"),
            Some(format!("(({rm} >> {}u) & 1u)", a - 1)),
        ),
    }
}

/// Try to inline one instruction. Returns false if a shell is required.
/// `body` receives statements WITHOUT the condition wrapper.
fn inline_body(cx: &Ctx, instr: &Instr) -> Option<String> {
    let mut s = String::new();
    match instr.op {
        Op::Alu {
            op,
            s: sflag,
            rd,
            rn,
            op2,
        } => {
            if rd == PC {
                return None;
            }
            let (bexpr, carry) = op2_exprs(cx, instr, op2)?;
            let a = cx.reg(rn, instr);
            let cin = "((c[16] >> 29) & 1u)";
            let logical_c = |s: &mut String, carry: &Option<String>| {
                if let Some(ce) = carry {
                    let _ = writeln!(s, "        f_c(c, {ce});");
                }
            };
            match op {
                AluOp::And
                | AluOp::Eor
                | AluOp::Orr
                | AluOp::Bic
                | AluOp::Mov
                | AluOp::Mvn
                | AluOp::Tst
                | AluOp::Teq => {
                    let expr = match op {
                        AluOp::And | AluOp::Tst => format!("({a} & {bexpr})"),
                        AluOp::Eor | AluOp::Teq => format!("({a} ^ {bexpr})"),
                        AluOp::Orr => format!("({a} | {bexpr})"),
                        AluOp::Bic => format!("({a} & ~{bexpr})"),
                        AluOp::Mov => bexpr.clone(),
                        _ => format!("(~{bexpr})"),
                    };
                    let _ = writeln!(s, "        uint32_t r = {expr};");
                    if sflag {
                        s.push_str("        f_nz(c, r);\n");
                        logical_c(&mut s, &carry);
                    }
                    if !op.is_compare() {
                        let _ = writeln!(s, "        c[{rd}] = r;");
                    } else {
                        s.push_str("        (void)r;\n");
                    }
                }
                AluOp::Add
                | AluOp::Adc
                | AluOp::Sub
                | AluOp::Sbc
                | AluOp::Rsb
                | AluOp::Rsc
                | AluOp::Cmp
                | AluOp::Cmn => {
                    let (x, y, ci) = match op {
                        AluOp::Add | AluOp::Cmn => (a.clone(), bexpr.clone(), "0u".to_string()),
                        AluOp::Adc => (a.clone(), bexpr.clone(), cin.to_string()),
                        AluOp::Sub | AluOp::Cmp => (a.clone(), format!("~{bexpr}"), "1u".into()),
                        AluOp::Sbc => (a.clone(), format!("~{bexpr}"), cin.to_string()),
                        AluOp::Rsb => (bexpr.clone(), format!("~{a}"), "1u".into()),
                        _ => (bexpr.clone(), format!("~{a}"), cin.to_string()),
                    };
                    if sflag {
                        let _ = writeln!(s, "        uint32_t r = op_adds(c, {x}, {y}, {ci});");
                    } else {
                        let _ = writeln!(s, "        uint32_t r = {x} + {y} + {ci};");
                    }
                    if !op.is_compare() {
                        let _ = writeln!(s, "        c[{rd}] = r;");
                    } else {
                        s.push_str("        (void)r;\n");
                    }
                }
            }
        }
        Op::Mul {
            acc,
            s: sflag,
            rd,
            rn,
            rs,
            rm,
        } => {
            if rd == PC {
                return None;
            }
            let _ = writeln!(s, "        uint32_t r = c[{rm}] * c[{rs}];");
            if acc {
                let _ = writeln!(s, "        r += c[{rn}];");
            }
            let _ = writeln!(s, "        c[{rd}] = r;");
            if sflag {
                s.push_str("        f_nz(c, r);\n");
            }
        }
        Op::MulLong {
            signed,
            acc,
            s: sflag,
            rd_hi,
            rd_lo,
            rs,
            rm,
        } => {
            let cast = if signed {
                "(int64_t)(int32_t)"
            } else {
                "(uint64_t)"
            };
            let _ = writeln!(
                s,
                "        uint64_t r = (uint64_t)({cast}c[{rm}] * {cast}c[{rs}]);"
            );
            if acc {
                let _ = writeln!(
                    s,
                    "        r += ((uint64_t)c[{rd_hi}] << 32) | (uint64_t)c[{rd_lo}];"
                );
            }
            let _ = writeln!(s, "        c[{rd_lo}] = (uint32_t)r;");
            let _ = writeln!(s, "        c[{rd_hi}] = (uint32_t)(r >> 32);");
            if sflag {
                s.push_str("        f_nz64(c, r);\n");
            }
        }
        Op::Mem {
            load,
            width,
            signed,
            rd,
            rn,
            offset,
            pre,
            up,
            writeback,
        } => {
            if rd == PC {
                return None;
            }
            let base = cx.reg(rn, instr);
            // Thumb PC-relative loads use the word-aligned base.
            let base = if cx.thumb && rn == PC {
                format!("(0x{:08x}u)", instr.pc_value() & !3)
            } else {
                base
            };
            let off = match offset {
                MemOffset::Imm(v) => format!("0x{v:x}u"),
                MemOffset::Reg { rm, shift } => match shift {
                    Shift::Imm { kind, amount } => {
                        if kind == ShiftKind::Ror && amount == 0 {
                            return None; // RRX offset: carry-coupled, shell
                        }
                        shift_exprs(&cx.reg(rm, instr), kind, amount).0
                    }
                    Shift::Reg { .. } => return None,
                },
            };
            let sign = if up { "+" } else { "-" };
            let _ = writeln!(s, "        uint32_t base = {base};");
            let _ = writeln!(s, "        uint32_t ob = base {sign} {off};");
            let _ = writeln!(
                s,
                "        uint32_t addr = {};",
                if pre { "ob" } else { "base" }
            );
            let do_wb = !pre || writeback;
            if load {
                let v = match (width, signed) {
                    (MemWidth::Word, _) => {
                        "ror32(a->read32(m, addr & ~3u), (addr & 3u) * 8u)".to_string()
                    }
                    (MemWidth::Half, false) => {
                        "ror32(a->read16(m, addr & ~1u), (addr & 1u) * 8u)".to_string()
                    }
                    (MemWidth::Half, true) => {
                        "((addr & 1u) ? (uint32_t)(int32_t)(int8_t)a->read8(m, addr) : (uint32_t)(int32_t)(int16_t)a->read16(m, addr))".to_string()
                    }
                    (MemWidth::Byte, false) => "a->read8(m, addr)".to_string(),
                    (MemWidth::Byte, true) => {
                        "(uint32_t)(int32_t)(int8_t)a->read8(m, addr)".to_string()
                    }
                };
                if do_wb && rn != rd && rn != PC {
                    let _ = writeln!(s, "        c[{rn}] = ob;");
                }
                let _ = writeln!(s, "        c[{rd}] = {v};");
            } else {
                let val = format!("c[{rd}]");
                match width {
                    MemWidth::Word => {
                        let _ = writeln!(s, "        a->write32(m, addr & ~3u, {val});");
                    }
                    MemWidth::Half => {
                        let _ = writeln!(s, "        a->write16(m, addr & ~1u, {val});");
                    }
                    MemWidth::Byte => {
                        let _ = writeln!(s, "        a->write8(m, addr, {val});");
                    }
                }
                if do_wb && rn != PC {
                    let _ = writeln!(s, "        c[{rn}] = ob;");
                }
            }
        }
        Op::BlockMem {
            load,
            rn,
            rlist,
            pre,
            up,
            s_bit,
            writeback,
        } => {
            if s_bit || rlist == 0 || rn == PC || (load && rlist & (1 << PC) != 0) {
                return None; // user-bank / empty list / pop{pc} handled elsewhere
            }
            let regs: Vec<u8> = (0..16).filter(|r| rlist & (1 << r) != 0).collect();
            let total = regs.len() as u32 * 4;
            let lowest = rlist.trailing_zeros() as u8;
            let _ = writeln!(s, "        uint32_t base = c[{rn}];");
            let start = match (up, pre) {
                (true, false) => "base".to_string(),
                (true, true) => "base + 4u".to_string(),
                (false, false) => format!("base - {total}u + 4u"),
                (false, true) => format!("base - {total}u"),
            };
            let wb_val = if up {
                format!("base + {total}u")
            } else {
                format!("base - {total}u")
            };
            let _ = writeln!(s, "        uint32_t addr = {start};");
            let rn_in_list = rlist & (1 << rn) != 0;
            if load {
                if writeback && !rn_in_list {
                    let _ = writeln!(s, "        c[{rn}] = {wb_val};");
                }
                for r in &regs {
                    let _ = writeln!(s, "        c[{r}] = a->read32(m, addr & ~3u); addr += 4u;");
                }
            } else {
                for r in &regs {
                    let val = if *r == PC {
                        format!("0x{:08x}u", instr.pc_value().wrapping_add(4))
                    } else if *r == rn {
                        if *r == lowest {
                            "base".to_string()
                        } else {
                            wb_val.clone()
                        }
                    } else {
                        format!("c[{r}]")
                    };
                    let _ = writeln!(s, "        a->write32(m, addr & ~3u, {val}); addr += 4u;");
                }
                if writeback {
                    let _ = writeln!(s, "        c[{rn}] = {wb_val};");
                }
            }
        }
        _ => return None,
    }
    Some(s)
}

/// Emit one block as a C function.
/// Chain-group context: the member key set of the group this block is
/// emitted into. Static transfers to members become gotos.
struct ChainCtx<'a> {
    members: &'a std::collections::HashSet<u32>,
}

fn label(key: u32) -> String {
    format!(
        "L_{:08x}_{}",
        key & !1,
        if key & 1 != 0 { "t" } else { "a" }
    )
}

/// Emit a static control transfer to `key` (caller has already set
/// c[15] and any link register): a direct goto when the target belongs
/// to the same chain group — gated on back-edges so native loops still
/// return for IRQ delivery and frame pacing — else a dispatcher return.
fn transfer(out: &mut String, chain: Option<&ChainCtx>, src_addr: u32, key: u32, ind: &str) {
    if let Some(ch) = chain {
        if ch.members.contains(&key) {
            if key & !1 <= src_addr {
                let _ = writeln!(out, "{ind}if (a->chain_gate(m)) return 0x{key:08x}u;");
            }
            let _ = writeln!(out, "{ind}goto {};", label(key));
            return;
        }
    }
    let _ = writeln!(out, "{ind}return 0x{key:08x}u;");
}

/// The dispatch keys this block can statically transfer to in its
/// emitted form (unconditional/taken branch targets, fused Thumb BL
/// targets, fall-through). May over-approximate (a fall-through that
/// emission turns into a shell exit) — used only to group blocks; the
/// emitter decides per-site whether a goto actually materializes.
pub fn static_exit_keys(b: &Block) -> Vec<u32> {
    let tb = b.thumb as u32;
    let n = b.instrs.len();
    let Some(last) = b.instrs.last() else {
        return Vec::new();
    };
    if n >= 2 {
        if let Some((target, _)) = armv4t::fuse_thumb_bl(&b.instrs[n - 2], last) {
            return vec![(target & !1) | 1];
        }
    }
    match last.op {
        Op::Branch { target, .. } => {
            let mut v = vec![target | tb];
            if last.cond != Cond::Al {
                v.push(last.addr.wrapping_add(last.size()) | tb);
            }
            v
        }
        Op::Bx { .. } | Op::Swi { .. } | Op::Undefined { .. } | Op::ThumbBlLow { .. } => Vec::new(),
        Op::Alu { rd, .. } if rd == PC => Vec::new(),
        Op::Mem { load: true, rd, .. } if rd == PC => Vec::new(),
        Op::BlockMem {
            load: true, rlist, ..
        } if rlist & (1 << PC) != 0 => Vec::new(),
        _ => vec![last.addr.wrapping_add(last.size()) | tb],
    }
}

fn emit_block(out: &mut String, b: &Block, view: &crate::analyze::View, chain: Option<&ChainCtx>) {
    let thumb_bit = b.thumb as u32;
    let region = (b.addr >> 24) as usize & 0xF;
    if chain.is_some() {
        // Group member: a labelled body inside the group function,
        // which owns the c/pc declarations.
        let _ = writeln!(out, "{}:;", label(b.key()));
    } else {
        let _ = writeln!(
            out,
            "uint32_t b_{:08x}_{}(const RtApi* a, void* m) {{\n    uint32_t* c = (uint32_t*)m;\n    uint32_t pc; (void)pc;",
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
    }

    // RAM-resident blocks were translated from a profiling snapshot;
    // guard the whole block's content (one FNV-1a hash call) so swapped
    // or overwritten code falls back to the interpreter instead of
    // running stale natives. First/last-word checks proved insufficient:
    // overlays routinely share prologue/epilogue words.
    // ROM and BIOS (region 0) are fixed images: no guard.
    if region != 8 && region != 0 {
        let last = b.instrs.last().unwrap();
        let len = last.addr.wrapping_add(last.size()).wrapping_sub(b.addr);
        match view.bytes(b.addr, len as usize) {
            Some(bytes) => {
                let hash = crate::fnv64(bytes);
                let _ = writeln!(
                    out,
                    "    if (!a->guard(m, 0x{:08x}u, {len}u, 0x{hash:016x}ull)) {{ c[15] = 0x{:08x}u; return a->interp_one(m); }}",
                    b.addr, b.addr
                );
            }
            None => {
                // The block's byte range runs past the snapshot slice
                // (e.g. decode walked to a mirror boundary): it cannot
                // be content-guarded, so it permanently defers to the
                // interpreter instead of running unguarded natives.
                let _ = writeln!(
                    out,
                    "    c[15] = 0x{:08x}u; return a->interp_one(m);",
                    b.addr
                );
                out.push_str(if chain.is_some() { "\n" } else { "}\n\n" });
                return;
            }
        }
    }

    let close: &str = if chain.is_some() { "\n" } else { "}\n\n" };
    let mut cx = Ctx {
        out,
        thumb: b.thumb,
        cycles: 0,
    };
    let mut i = 0;
    while i < b.instrs.len() {
        let instr = &b.instrs[i];
        let next = instr.addr.wrapping_add(instr.size());
        let expect = next | thumb_bit;
        let last = i + 1 == b.instrs.len();
        let cost = gba_core::machine_instr_cost(region, instr);

        // Fused Thumb BL pair (always unconditional).
        if let Op::ThumbBlHigh { .. } = instr.op {
            if i + 1 < b.instrs.len() {
                if let Some((target, ret)) = armv4t::fuse_thumb_bl(instr, &b.instrs[i + 1]) {
                    cx.cycles += cost + gba_core::machine_instr_cost(region, &b.instrs[i + 1]);
                    cx.flush_ticks();
                    let _ = writeln!(cx.out, "    c[14] = 0x{ret:08x}u;");
                    let _ = writeln!(cx.out, "    c[15] = 0x{:08x}u;", target & !1);
                    transfer(cx.out, chain, b.addr, (target & !1) | 1, "    ");
                    cx.out.push_str(close);
                    return;
                }
            }
            emit_shell(&mut cx, instr, expect, last);
            i += 1;
            continue;
        }

        // Control flow.
        match instr.op {
            Op::Branch { link, target } => {
                cx.cycles += cost;
                cx.flush_ticks();
                let key = target | thumb_bit;
                let guard = instr.cond != Cond::Al;
                if guard {
                    // A taken conditional BL links like any BL — LR must
                    // be written inside the taken arm (hand-written
                    // assembly uses bl<cond>; compilers never emit it,
                    // which long hid this path).
                    let lr = if link {
                        format!("c[14] = 0x{:08x}u; ", instr.addr.wrapping_add(4))
                    } else {
                        String::new()
                    };
                    let _ = writeln!(
                        cx.out,
                        "    {{ uint32_t s_ = c[16]; uint32_t cn = s_ >> 31, cz = (s_ >> 30) & 1u, cc = (s_ >> 29) & 1u, cv = (s_ >> 28) & 1u;\n      if {} {{ {lr}c[15] = 0x{:08x}u;",
                        cond_expr(instr.cond),
                        target
                    );
                    transfer(cx.out, chain, b.addr, key, "        ");
                    cx.out.push_str("      } }\n");
                    i += 1;
                    continue;
                }
                if link {
                    let _ = writeln!(cx.out, "    c[14] = 0x{:08x}u;", instr.addr.wrapping_add(4));
                }
                let _ = writeln!(cx.out, "    c[15] = 0x{:08x}u;", target);
                transfer(cx.out, chain, b.addr, key, "    ");
                cx.out.push_str(close);
                return;
            }
            // BIOS (region 0) blocks shell their indirect exits instead:
            // the protection value (`bios_open`) must equal the last
            // fetched BIOS opcode when control leaves the BIOS, and the
            // interp shell's fetch hook maintains it exactly. Branches
            // stay native (they are intra-BIOS).
            Op::Bx { rm } if instr.cond == Cond::Al && region != 0 => {
                cx.cycles += cost;
                cx.flush_ticks();
                let t = cx.reg(rm, instr);
                let _ = writeln!(
                    cx.out,
                    "    {{ uint32_t t = {t};\n      if (t & 1u) {{ c[16] |= 0x20u; c[15] = t & ~1u; return (t & ~1u) | 1u; }}\n      c[16] &= ~0x20u; c[15] = t & ~3u; return t & ~3u; }}"
                );
                cx.out.push_str(close);
                return;
            }
            // pop {.., pc} (no state switch on v4T).
            Op::BlockMem {
                load: true,
                rn,
                rlist,
                pre: false,
                up: true,
                s_bit: false,
                writeback: true,
            } if instr.cond == Cond::Al && rlist & (1 << PC) != 0 && rn != PC && region != 0 => {
                cx.cycles += cost;
                cx.flush_ticks();
                let regs: Vec<u8> = (0..15).filter(|r| rlist & (1 << r) != 0).collect();
                let total = (regs.len() as u32 + 1) * 4;
                let _ = writeln!(cx.out, "    {{ uint32_t addr = c[{rn}];");
                for r in &regs {
                    let _ = writeln!(
                        cx.out,
                        "      c[{r}] = a->read32(m, addr & ~3u); addr += 4u;"
                    );
                }
                let _ = writeln!(cx.out, "      c[{rn}] = c[{rn}] + {total}u;");
                let mask = if b.thumb { "~1u" } else { "~3u" };
                let _ = writeln!(
                    cx.out,
                    "      c[15] = a->read32(m, addr & ~3u) & {mask}; return c[15] | {thumb_bit}u; }}"
                );
                cx.out.push_str(close);
                return;
            }
            _ => {}
        }

        // Straight-line instruction: inline or shell.
        let touches_bus = matches!(instr.op, Op::Mem { .. } | Op::BlockMem { .. });
        match inline_body(&cx, instr) {
            Some(body) if instr.cond == Cond::Al => {
                if touches_bus {
                    cx.flush_ticks();
                }
                cx.cycles += cost;
                let _ = writeln!(cx.out, "    {{\n{body}    }}");
            }
            Some(body) => {
                if touches_bus {
                    cx.flush_ticks();
                }
                cx.cycles += cost;
                let _ = writeln!(
                    cx.out,
                    "    {{ uint32_t s_ = c[16]; uint32_t cn = s_ >> 31, cz = (s_ >> 30) & 1u, cc = (s_ >> 29) & 1u, cv = (s_ >> 28) & 1u;\n      if {} {{\n{body}      }} }}",
                    cond_expr(instr.cond)
                );
            }
            None => {
                emit_shell(&mut cx, instr, expect, last);
                if last {
                    cx.out.push_str(close);
                    return;
                }
            }
        }
        i += 1;
    }

    // Fell off the end: continue at the next address.
    if let Some(last) = b.instrs.last() {
        let next = last.addr.wrapping_add(last.size());
        cx.flush_ticks();
        let _ = writeln!(cx.out, "    c[15] = 0x{next:08x}u;",);
        transfer(cx.out, chain, b.addr, next | thumb_bit, "    ");
    }
    out.push_str(close);
}

/// Emit translated C in translation units of at most ~`max_bytes` each,
/// handing each finished unit to `sink`. Bounding the unit size bounds the
/// system C compiler's memory: a full-image translation can exceed the
/// source image by two orders of magnitude, and feeding that to cc as one
/// unit makes its optimizer balloon. Block functions have external
/// linkage; the final unit re-declares them and builds the lookup table.
/// `sink` also receives the number of blocks emitted so far (out of
/// `analysis.blocks.len()`), so callers can report build progress.
/// Returns the number of units emitted.
/// Group ROM blocks into chain groups: connected components over the
/// static-transfer edges, split to a bounded size so no C function gets
/// unwieldy. Within a group, static transfers become gotos (back-edges
/// gated); everything else still returns to the dispatcher. RAM blocks
/// stay solo: their entry guards and the audio-HLE hook keys depend on
/// per-entry dispatch.
fn chain_groups(blocks: &[Block]) -> Vec<Vec<usize>> {
    const GROUP_MAX_INSTRS: usize = 8192;
    let key_idx: std::collections::HashMap<u32, usize> = blocks
        .iter()
        .enumerate()
        .map(|(i, b)| (b.key(), i))
        .collect();
    // Union-find.
    let mut parent: Vec<usize> = (0..blocks.len()).collect();
    fn find(parent: &mut Vec<usize>, mut i: usize) -> usize {
        while parent[i] != i {
            parent[i] = parent[parent[i]];
            i = parent[i];
        }
        i
    }
    for (i, b) in blocks.iter().enumerate() {
        if b.addr >> 24 != 8 {
            continue;
        }
        for key in static_exit_keys(b) {
            if let Some(&j) = key_idx.get(&key) {
                if blocks[j].addr >> 24 == 8 {
                    let (ri, rj) = (find(&mut parent, i), find(&mut parent, j));
                    if ri != rj {
                        parent[ri] = rj;
                    }
                }
            }
        }
    }
    let mut by_root: std::collections::BTreeMap<usize, Vec<usize>> = Default::default();
    for i in 0..blocks.len() {
        let r = find(&mut parent, i);
        by_root.entry(r).or_default().push(i);
    }
    // Split oversized components by address order: locality keeps the
    // gotos that matter (loops are address-adjacent) inside one part.
    let mut groups = Vec::new();
    for (_, mut members) in by_root {
        members.sort_by_key(|&i| blocks[i].key());
        let mut cur = Vec::new();
        let mut instrs = 0usize;
        for i in members {
            if instrs + blocks[i].instrs.len() > GROUP_MAX_INSTRS && !cur.is_empty() {
                groups.push(std::mem::take(&mut cur));
                instrs = 0;
            }
            instrs += blocks[i].instrs.len();
            cur.push(i);
        }
        if !cur.is_empty() {
            groups.push(cur);
        }
    }
    groups
}

/// Emit one chain group: a static function holding every member body
/// (entered through a small switch), plus the externally-linked
/// per-member forwarders the block table points at.
fn emit_group(out: &mut String, blocks: &[Block], members: &[usize], view: &crate::analyze::View) {
    let keys: std::collections::HashSet<u32> = members.iter().map(|&i| blocks[i].key()).collect();
    let gid = blocks[members[0]].key();
    let _ = writeln!(
        out,
        "static uint32_t g_{gid:08x}(const RtApi* a, void* m, uint32_t entry) {{\n    uint32_t* c = (uint32_t*)m;\n    uint32_t pc; (void)pc;\n    switch (entry) {{"
    );
    for (n, &i) in members.iter().enumerate() {
        let _ = writeln!(out, "    case {n}u: goto {};", label(blocks[i].key()));
    }
    out.push_str("    default: return 0u;\n    }\n");
    let chain = ChainCtx { members: &keys };
    for &i in members {
        emit_block(out, &blocks[i], view, Some(&chain));
    }
    out.push_str("}\n\n");
    for (n, &i) in members.iter().enumerate() {
        let b = &blocks[i];
        let _ = writeln!(
            out,
            "uint32_t b_{:08x}_{}(const RtApi* a, void* m) {{ return g_{gid:08x}(a, m, {n}u); }}",
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
    }
    out.push('\n');
}

pub fn emit_c_chunked(
    analysis: &Analysis,
    view: &crate::analyze::View,
    max_bytes: usize,
    mut sink: impl FnMut(&str, usize) -> Result<(), String>,
) -> Result<usize, String> {
    let mut count = 0usize;
    let mut out = String::with_capacity(4 << 20);
    out.push_str(PREAMBLE);
    out.push('\n');

    let mut done = 0usize;
    for members in chain_groups(&analysis.blocks) {
        if members.len() == 1 {
            emit_block(&mut out, &analysis.blocks[members[0]], view, None);
        } else {
            emit_group(&mut out, &analysis.blocks, &members, view);
        }
        done += members.len();
        if out.len() >= max_bytes {
            sink(&out, done)?;
            count += 1;
            out.clear();
            out.push_str(PREAMBLE);
            out.push('\n');
        }
    }

    for b in &analysis.blocks {
        let _ = writeln!(
            out,
            "extern uint32_t b_{:08x}_{}(const RtApi* a, void* m);",
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
    }
    out.push_str("RCG_EXPORT const RcgBlock rcg_blocks[] = {\n");
    for b in &analysis.blocks {
        let _ = writeln!(
            out,
            "    {{ 0x{:08x}u, b_{:08x}_{} }},",
            b.key(),
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
    }
    out.push_str("};\n");
    let _ = writeln!(
        out,
        "RCG_EXPORT const uint64_t rcg_block_count = {};",
        analysis.blocks.len()
    );
    sink(&out, analysis.blocks.len())?;
    Ok(count + 1)
}
