//! C11 emission.
//!
//! v0 ("shell" translation): every instruction executes through the
//! runtime's `interp_one`, with a PC check after each step — any
//! divergence (taken conditional, call, computed branch, interrupt-free
//! fall-out) returns to the dispatcher. This proves the full pipeline
//! (analysis → C → cc → dlopen → guest-address lookup → differential
//! parity with the interpreter) before instruction-class inlining lands.
//!
//! Output layout: one C function per basic block plus the exported
//! lookup table `rcg_blocks` / `rcg_block_count`, keyed by guest address
//! with bit 0 = Thumb.

use std::fmt::Write;

use crate::analyze::Analysis;

pub fn emit_c(analysis: &Analysis) -> String {
    let mut out = String::with_capacity(1 << 20);
    out.push_str(
        "// Generated by recomp — derivative of the input image; do not distribute.\n\
         #include <stdint.h>\n\n\
         typedef struct { uint32_t (*interp_one)(void*); } RtApi;\n\
         typedef struct { uint32_t key; uint32_t (*fn)(const RtApi*, void*); } RcgBlock;\n\n",
    );

    for b in &analysis.blocks {
        let _ = writeln!(
            out,
            "static uint32_t b_{:08x}_{}(const RtApi* a, void* m) {{",
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
        out.push_str("    uint32_t pc;\n");
        let mut next = b.addr;
        for (i, instr) in b.instrs.iter().enumerate() {
            next = next.wrapping_add(instr.size());
            let expect = next | b.thumb as u32;
            if i + 1 == b.instrs.len() {
                out.push_str("    pc = a->interp_one(m);\n    return pc;\n");
            } else {
                let _ = writeln!(
                    out,
                    "    pc = a->interp_one(m); if (pc != 0x{expect:08x}u) return pc;"
                );
            }
        }
        out.push_str("}\n\n");
    }

    out.push_str("const RcgBlock rcg_blocks[] = {\n");
    for b in &analysis.blocks {
        let _ = writeln!(
            out,
            "    {{ 0x{:08x}u, b_{:08x}_{} }},",
            b.key(),
            b.addr,
            if b.thumb { "t" } else { "a" }
        );
    }
    out.push_str("};\n");
    let _ = writeln!(out, "const uint64_t rcg_block_count = {};", analysis.blocks.len());
    out
}
